[build]
  publish = "./" # 프로젝트 루트 디렉토리를 Publish Directory로 설정

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18.17.1" # 프로젝트에서 요구하는 Node.js 버전 지정
